### ISSUE TITLE
Build script fails on arm mac with with zsh

### ISSUE THREAD

**Issue by paul-brenner** [MrMarble/zmk-viewer#16]
Figured I should say something instead of just troubleshooting past it and not mentioning the errors. First mktemp fails complaining: 
mktemp: illegal option -- -
I tried replacing --directory with -d in the script and the next failure is giving me
```

[/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.P70W3vh4/zmk-viewer-1.5.0-darwin-amd64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.P70W3vh4/zmk-viewer-1.5.0-darwin-amd64.zip or
        /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.P70W3vh4/zmk-viewer-1.5.0-darwin-amd64.zip.zip, and cannot find /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.P70W3vh4/zmk-viewer-1.5.0-darwin-amd64.zip.ZIP, period.
```

I was going to just look through the script and do things manually but maybe if I can make time I'll see if I can propose changes to the instal script that get it working on my system. TBD

**Comment by paul-brenner** [comment]
created a pull request here https://github.com/MrMarble/zmk-viewer/pull/17

**Comment by MrMarble** [comment]
#17 was merged!
