### ISSUE TITLE
Add build/install instructions

### ISSUE THREAD

**Issue by notfed** [MrMarble/zmk-viewer#6]
This project sounds great but I have no idea how to build or install it.

**Comment by MrMarble** [comment]
Thank you for your feedback! I should improve the README, I've been busy with other projects...

Installation is simple, just download the portable executable for your operating system from https://github.com/MrMarble/zmk-viewer/releases, extract it and run it from the command line.

If you want to build it yourself, you need Go, simply clone the repo and run `go build ./cmd/zmk-viewer`
